services:
  postgres:
    image : postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER : jjsh0208
      POSTGRES_PASSWORD : Gusdk5540!
      POSTGRES_DB : board_api
    ports:
      - "5432:5432"
    networks:
      - "app-network"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  springboot:
    build: ./ # 스프링부트 앱이 있는 디렉토리
    container_name: board-api-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/board_api
      SPRING_DATASOURCE_USERNAME: jjsh0208
      SPRING_DATASOURCE_PASSWORD: Gusdk5540!
    ports:
      - "8080"8080"
    depends_on:
      - postgres
    networks:
      - "app-network"
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: