server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: "board_API"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-container:5432/board_api
    username: jjsh0208
    password: Gusdk5540!

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  jwt:
    secretKey: L@4mV9eZ*R1z#3Tq6!P5jY2wF8xL7d$Q9%kH1xA6^bL0*H4mJ9!nT3zP6q^Y8uB7#xJ2vM4@fH5cT3r!D6sN9%tL2
    validityInMilliseconds: 3600000


upload:
  directory: "/var/lib/app/upload/image/"
